# Generated by Django 5.2.1 on 2025-05-13 08:44

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Document title')),
                ('file', models.FileField(upload_to=documents.models.document_upload_path, verbose_name='Document file')),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('jpg', 'JPG'), ('jpeg', 'JPEG')], max_length=10, verbose_name='File format')),
                ('text_content', models.TextField(blank=True, verbose_name='Extracted text content')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Upload date')),
                ('size', models.PositiveIntegerField(verbose_name='File size (bytes)')),
            ],
        ),
    ]
